# Generated by Django 5.0.3 on 2024-03-13 07:01

import django.utils.timezone
import model_utils.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OldEmployee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('first_name', models.CharField(max_length=10)),
                ('last_name', models.CharField(max_length=10)),
                ('mobile_no', models.CharField(max_length=10, unique=True)),
                ('date_of_joined', models.DateField()),
                ('date_of_release', models.DateField()),
                ('address', models.CharField(max_length=50)),
                ('identity_card', models.FileField(upload_to='')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
